In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
#a)
add_arr=arr+1
print('After adding 1:',add_arr)
#b)
mul_arr=arr*3
print("After multiplying by 3:", mul_arr)
#c)
div_arr = arr / 2
print("After dividing by 2:", div_arr)




[1 2 3 4 5]
After adding 1: [2 3 4 5 6]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [17]:
#2a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = np.flip(arr)
print("Reversed array:", reversed_arr)




Reversed array: [5 4 6 3 2 1]


In [21]:

#b)
from collections import Counter
g =np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
h =np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
i = Counter(g)
j = i.most_common(1)[0][0]
k =np.where(g == j)[0]
l =Counter(h)
m =l.most_common(1)[0][0]
n = np.where(h == m)[0]
print("Most Frequent Element in g:", j, "Indices:", k)
print("Most Frequent Element in h:", m, "Indices:", n)

Most Frequent Element in g: 1 Indices: [0 5 7 8 9]
Most Frequent Element in h: 1 Indices: [0 1 2]


In [23]:
arr =np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) 1st row, 2nd column
print("1st row, 2nd column:", arr[0, 1])

# b) 3rd row, 1st column
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [13]:
Priyam = np.linspace(10, 100, 25)
print("Dimensions:", Priyam.ndim)
print("Shape:", Priyam.shape)
print("Total elements:",  Priyam .size)
print("Data type:",  Priyam .dtype)
print("Total bytes:",  Priyam.nbytes)

transposed_reshape =  Priyam.reshape(-1, 1).T  
print("Transposed with reshape:\n", transposed_reshape)

transposed_T = Priyam .reshape(1, -1).T
print("Transposed with T attribute:\n", transposed_T)


Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transposed with reshape:
 [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transposed with T attribute:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [25]:
# Create array
ucs420_Priyam =np.array([[10,20,30,40], [50,60,70,80], [90,15,20,35]])

# Compute stats
print("Mean:", np.mean(ucs420_Priyam))
print("Median:", np.median(ucs420_Priyam))
print("Max:", np.max(ucs420_Priyam))
print("Min:", np.min(ucs420_Priyam))
print("Unique elements:", np.unique(ucs420_Priyam))

# Reshape to 4x3
reshaped_ucs420_Priyam = ucs420_Priyam.reshape(4, 3)
print("Reshaped (4x3):\n", reshaped_ucs420_Priyam)

# Resize to 2x3
resized_ucs420_Priyam = np.resize(ucs420_Priyam, (2, 3))
print("Resized (2x3):\n", resized_ucs420_Priyam)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3):
 [[10 20 30]
 [40 50 60]]
